name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: mv ./src ./dist
      - uses: actions/checkout@v2
        with:
          ref: pages
          clean: false
      - run: |
          rm -f *.css *.js *.html *.svg
          mv ./dist/* ./
      - run: |
          git config user.name "Yoshihiro Tanaka"
          git config user.email "contact@cordea.jp"
          git add *.html *.css *.svg
          git commit -m "update"
          git push
