name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global yarn
      - run: yarn
      - run: yarn build --config ./webpack.prod.js
      - uses: actions/checkout@v2
        with:
          ref: pages
          clean: false
      - run: mv ./dist/* ./
      - run: |
          git config user.name "Yoshihiro Tanaka"
          git config user.email "contact@cordea.jp"
          git add *.html *.js *.css
          git commit -m "update"
          git push
